sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

baseurl: https://msbandofchoctawindians.github.io/cif-2024