sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

domain: msbandofchoctawindians.github.io
url: https://msbandofchoctawindians.github.io
baseurl: /cif-2024/